import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from 'next';

import './globals.css';
import { Providers } from '@/app/providers';
import { NavProvider } from '@/shared/context';
import { Header, Sidebar, Footer } from '@/widgets/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // 1. localStorage에서 저장된 테마 모드 확인
                  const savedMode = localStorage.getItem('themeMode');

                  if (savedMode === 'light') {
                    document.documentElement.setAttribute('data-theme', 'pastel');
                    return;
                  }

                  if (savedMode === 'dark') {
                    document.documentElement.setAttribute('data-theme', 'forest');
                    return;
                  }

                  // 2. system 또는 없으면 OS 다크모드 설정 확인
                  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  const theme = prefersDark ? 'forest' : 'pastel';
                  document.documentElement.setAttribute('data-theme', theme);
                } catch {
                  // 3. 실패 시 기본값 (pastel)
                  document.documentElement.setAttribute('data-theme', 'pastel');
                }
              })();
            `,
          }}
        />
      </head>
      <body className="antialiased min-h-dvh">
        <Providers>
          <NavProvider>
            <a
              href="#main"
              className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 btn btn-sm"
            >
              본문 바로가기
            </a>
            <div className="drawer">
              <input id="app-drawer" type="checkbox" className="drawer-toggle" />
              <div className="drawer-content flex flex-col min-h-dvh">
                <Header />
                <main
                  id="main"
                  className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 flex-1 w-full"
                >
                  {children}
                </main>
                <Footer />
              </div>
              <div className="drawer-side z-60">
                <label
                  htmlFor="app-drawer"
                  aria-label="close sidebar"
                  className="drawer-overlay"
                ></label>
                <Sidebar />
              </div>
            </div>
          </NavProvider>
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
