#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run Prettier and ESLint auto-fix on staged files
npx lint-staged

# Run steiger architecture check
pnpm steiger

# Run ESLint and TypeScript check (full project)
pnpm check
